### ISSUE TITLE
XRM API functions can fail when reading from socket fails with EINTR

### ISSUE THREAD

**Issue by ev-zhuravlev** [Xilinx/XRM#3] opened 2022-12-15 08:50 UTC
In rare circumstances ctx->socket->read_some in xrmJsonRequest can fail with EINTR aka boost::asio::error::interrupted.
Instead of continuing reading XRM fails an API function.

**Comment by bttu** [comment] 2022-12-20 18:03
@ev-zhuravlev Can you share the test case on how to reproduce the issue?

**Comment by ev-zhuravlev** [comment] 2023-02-21 16:40
I was not able to reproduce this on single session but I was testing 15 concurrent encoding session creation, video encoding and destruction for 8 hours.
A couple of times during this 8-hour stress tests creation process xrmCuListAlloc was failing because this call
https://github.com/Xilinx/XRM/blob/master/src/lib/xrm.cpp#L283
was returning boost::asio::error::interrupted.
I have edited xrm.cpp for handling boost::asio::error::interrupted and the problem went away.

OS info:
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	OracleServer
Description:	Oracle Linux Server release 7.9
Release:	7.9
Codename:	n/a

It is Amazon EC2 VT1 instance.

**Comment by bttu** [comment] 2023-02-21 18:04
@ev-zhuravlev  Thanks for getting back with more information about this issue. It looks like you're running with a new OS (Oracle Linux Server 7.9) which was not covered on the VT1 verified OS list. Would you post the change you made for this boost::asio::error::interrupted issue?

**Comment by ev-zhuravlev** [comment] 2023-02-27 08:56
diff --git a/src/lib/xrm.cpp b/src/lib/xrm.cpp
index 41b3bef..ba17668 100644
--- a/src/lib/xrm.cpp
+++ b/src/lib/xrm.cpp
@@ -280,13 +280,26 @@ static int32_t xrmJsonRequest(xrmContext context, const char* jsonReq, char* jso
         unsigned char tmp[4];
         int32_t total_len = 0;
         int32_t cur_len = 0;
+        while (true)
+        {
         cur_len = ctx->socket->read_some(boost::asio::buffer(tmp, 4), ec);
-        if (cur_len != 4 || ec ) return XRM_ERROR;
+            if ( ec == boost::asio::error::interrupted )
+                continue;
+            if ( ec ) {
+                xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s length reading error: %d\n", __func__, ec);
+                return XRM_ERROR;
+            }
+            break;
+        }
+        if (cur_len != 4 ) {
+            xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s unexpected read length: %d\n", __func__, cur_len);
+            return XRM_ERROR;
+        }
         total_len = tmp[0] | (int32_t(tmp[1]) << 8) | (int32_t(tmp[2]) << 16) | (int32_t(tmp[3]) << 24);
         cur_len = 0;
         while (true) {
             replyLength = ctx->socket->read_some(boost::asio::buffer(jsonRsp + cur_len, maxLength - cur_len), ec);
-            if (ec) {
+            if (ec && ec != boost::asio::error::interrupted) {
                 xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s read error: %d\n", __func__, ec);
                 return XRM_ERROR;
             }

**Comment by ev-zhuravlev** [comment] 2023-02-27 08:59
diff --git a/src/lib/xrm.cpp b/src/lib/xrm.cpp
    index 41b3bef..ba17668 100644
    --- a/src/lib/xrm.cpp
    +++ b/src/lib/xrm.cpp
    @@ -280,13 +280,26 @@ static int32_t xrmJsonRequest(xrmContext context, const char* jsonReq, char* jso
             unsigned char tmp[4];
             int32_t total_len = 0;
             int32_t cur_len = 0;
    +        while (true)
    +        {
                 cur_len = ctx->socket->read_some(boost::asio::buffer(tmp, 4), ec);
    -            if (cur_len != 4 || ec ) return XRM_ERROR;
    +            if ( ec == boost::asio::error::interrupted )
    +                continue;
    +            if ( ec ) {
    +                xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s length reading error: %d\n", __func__, ec);
    +                return XRM_ERROR;
    +            }
    +            break;
    +        }
    +        if (cur_len != 4 ) {
    +            xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s unexpected read length: %d\n", __func__, cur_len);
    +            return XRM_ERROR;
    +        }
             total_len = tmp[0] | (int32_t(tmp[1]) << 8) | (int32_t(tmp[2]) << 16) | (int32_t(tmp[3]) << 24);
             cur_len = 0;
             while (true) {
                 replyLength = ctx->socket->read_some(boost::asio::buffer(jsonRsp + cur_len, maxLength - cur_len), ec);
    -            if (ec) {
    +            if (ec && ec != boost::asio::error::interrupted) {
                     xrmLog(ctx->xrmLogLevel, XRM_LOG_ERROR, "%s read error: %d\n", __func__, ec);
                     return XRM_ERROR;
                 }

**Comment by bttu** [comment] 2023-02-27 17:33
@ev-zhuravlev Thanks for sharing the code change. I'll look into the detailed change and get back. thanks!

**Comment by bttu** [comment] 2023-02-28 19:20
@ev-zhuravlev The logic looks good, Do you want to raise PR for it? Some minor comments regarding the code change:
+            if ( ec == boost::asio::error::interrupted ) <-- to remove the space before "ec" and after "interrupted"

similar to above for lines:
+        if (cur_len != 4 ) {
+            if ( ec ) {

And please add some comments for the code logic.

**Comment by bttu** [comment] 2023-03-20 16:32
@ev-zhuravlev Would you create one PR for the code change?

**Comment by bttu** [comment] 2023-03-27 18:09
@ev-zhuravlev Would you share your feedback that whether you'd like to create a PR for the code change (which I prefer) or you're fine with others integrating the fix? Thanks a million.

**Comment by ev-zhuravlev** [comment] 2023-03-28 12:23
Sorry for the delay.
I have created the PR.

**Comment by bttu** [comment] 2023-03-28 16:44
Thanks for the contribution. The PR is merged.

**Closed as completed** 2023-03-28 16:45 UTC
